---
# Docker Compose 2.4 is for local development
# https://www.heroku.com/podcasts/codeish/57-discussing-docker-containers-and-kubernetes-with-a-docker-captain - Source on that.
version: '2.4'

x-app: &app
  image: bridgetown:0.1.0
  mem_limit: 512m
  build:
    context: .
    dockerfile: Dockerfile
    # Targeting the development stage won't run bundle/yarn when building the docker image.
    # It means you can add a new gem or NPM package without having to wait for docker to rebuild.
    target: development
  volumes:
    - .:/usr/src/app:cached
    # Cache package folders so they persist between runs.
    - bundler:/usr/local/bundle:delegated
    - node_modules:/usr/src/app/node_modules:delegated
  tmpfs:
    - /tmp

services:
  web:
    <<: *app
    command: >
      bash -c "bundle check || bundle install &&
      yarn install --check-files &&
      yarn start --host '0.0.0.0'"
    ports:
      - "${PORT:-4000}:4000"
      - "4001:4001"
      - "4002:4002"

volumes:
  bundler:
  node_modules: 
